<?php
session_start();
require 'phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;
include_once 'dbconnect.php';
$side="";
$req = $_GET ['req'];
$result = mysqli_query($con, "SELECT * FROM data WHERE name LIKE '%{$req}%'");
if($row = mysqli_fetch_array($result)){
  $id = $row['id'];
  $name = $row['name'];
  $description = $row['description'];
  $branch = $row['branch'];
  $year = $row['year'];
  $user = $row['user'];
  $comment = $row['comment'];
}
$result_user = mysqli_query($con, "SELECT * FROM users WHERE name ='$user'");
$row = mysqli_fetch_array($result_user);
$user_email = $row['email'];
$related = split(" ", $req);
$resultside = mysqli_query($con, "SELECT * FROM data WHERE name LIKE'%{$related[0]}%'");
while($row = mysqli_fetch_array($resultside)) {
  if($row['status'] == "publish"){
  $side .= "<div class='search-result-1'><a href = '/post?req={$row['name']}'><h7 style='font-size:25px;'>{$row['name']}</h7><br></a><h7 style='color:green;font-size:12px;'>http://semcrack.com/search?req={$row['name']}</h7><br><h7 style='font-size:17px;'>{$row['description']}</h7><br><h7 style='font-size:15px;'>{$row['branch']}</h7><br><h7 style='font-size:13px;'>Share by : {$row['user']}</h7></div>";
  }
}
date_default_timezone_set('Asia/Kolkata');
$date = date("M j, Y @ g:i a");
if(isset($_POST['submit'])){
	$new_comment = $comment.'<div style = "margin-top:10px;"><img style="width:50px; border-radius:50%;display:inline-block;vertical-align:top;" src ="/assets/img/usr/'.$_SESSION['usr_id'].'.jpg" onError = this.onerror=null;this.src="/assets/img/usr/sample.png"; ><div class="dialogbox" style = "display:inline-block;"><div class="body"><a onclick="reply()" class="reply" style="float:right;"><i class="small material-icons">reply</i></a><span class="tip tip-left"></span><div class="message"><span>'.$_SESSION['usr_name'].' '.$date.'</span><hr><span>'.$_POST['comment'].'</span></div></div></div></div>';
	$query="UPDATE data SET comment= '{$new_comment}' WHERE id = {$id}";
	if(mysqli_query($con,$query) && $_SESSION['usr_name']!= $user){
		$mail->isSMTP();                                     
  		$mail->Host = 'smtp.gmail.com'; 
  		$mail->SMTPAuth = true; 
  		$mail->Username = 'semcrack17@gmail.com';                 
  		$mail->Password = 'Semcrack@17';                           
  		$mail->SMTPSecure = 'ssl'; 
  		$mail->Port = 465;  
  		$mail->setFrom("support@semcrack.com", "SemCrack");
  		$mail->addAddress($user_email);   
  		$mail->addReplyTo("support@semcrack.com", "SemCrack");
  		$mail->isHTML(true);                     
		$mail->Subject = "Comment";
		$mail->Body    = "Hello {$user},<br>Someone commented on your post and comment is <br><br> {$_POST['comment']} <br><br> <a href = 'http://semcrack.com/post?req={$name}'>http://semcrack.com/post?req={$name}</a><br><br>NOTE: Do not reply to this mail because it is an autogenerated mail.<br><br><br>Thank you<br>Team SemCrack" ;
		$mail->AltBody = '';
		$mail->send();
	}
	header("Refresh:0");
}

if(isset($_POST['submit1'])){
  $new_comment = $comment.'<div style = "margin-top:10px;"><img style="width:50px; border-radius:50%;display:inline-block;vertical-align:top;" src ="/assets/img/usr/sample.png" ><div class="dialogbox" style = "display:inline-block;"><div class="body"><a onclick="reply()" class="reply" style="float:right;"><i class="small material-icons">reply</i></a><span class="tip tip-left"></span><div class="message"><span>'.$_POST['name'].' '.$date.'</span><hr><span>'.$_POST['comment'].'</span></div></div></div></div>';
  $query="UPDATE data SET comment= '{$new_comment}' WHERE id = {$id}";
  if(mysqli_query($con,$query) && $_SESSION['usr_name']!= $user){
    $mail->isSMTP();                                     
      $mail->Host = 'smtp.gmail.com'; 
      $mail->SMTPAuth = true; 
      $mail->Username = 'semcrack17@gmail.com';                 
      $mail->Password = 'Semcrack@17';                           
      $mail->SMTPSecure = 'ssl'; 
      $mail->Port = 465;  
      $mail->setFrom("support@semcrack.com", "SemCrack");
      $mail->addAddress($user_email);   
      $mail->addReplyTo("support@semcrack.com", "SemCrack");
      $mail->isHTML(true);                     
    $mail->Subject = "Comment";
    $mail->Body    = "Hello {$user},<br>Someone commented on your post and comment is <br><br> {$_POST['comment']} <br><br> <a href = 'http://semcrack.com/post?req={$name}'>http://semcrack.com/post?req={$name}</a><br><br>NOTE: Do not reply to this mail because it is an autogenerated mail.<br><br><br>Thank you<br>Team SemCrack" ;
    $mail->AltBody = '';
    $mail->send();
  }
  header("Refresh:0");
}

?>
<html>
<head>
  <title>SemCrack</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src = "/js/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src = "/js/umd/popper.min.js"></script>
  <script type="text/javascript" src = "/js/bootstrap.js"></script>
  <link rel = "stylesheet" href = "/css/milligram.css"></link>
  <link rel = "stylesheet" href = "/css/set1.css"></link>
  <link rel = "stylesheet" href = "/css/style.css"></link>
  <link rel = "stylesheet" href = "/css/bootstrap.css"></link>
  </head>
  <style>
    @media screen and (min-width: 640px){
      body{
        background-color: #f7f7f7;
      }
      .shadow{
        box-shadow: 0 1px 6px rgba(32, 33, 36, 0.28);
      }
    }
    @media screen and (max-width: 640px){
      body{
        background-color: #fff;
      }
    }
  </style>
  <body>
    <?php include_once "navbar.php"; ?>
    <section class = "hello10">
      <div class="postcontent shadow" style="margin-bottom: 50px;">
      <div class = "post">
          <center><h1><?php echo $name;?></h1></center><br>
          <h4><?php echo $description?></h4><br>
          <center><button onclick="window.location.href='/assets/data/<?php echo $id;?>.pdf'">Preview</button>&nbsp;&nbsp;<a href='/assets/data/<?php echo $id;?>.pdf' download><button>Download</button></a>
          <a href = "/assets/data/<?php echo $id;?>.pdf"></a></center><br>
          <h5>Branch&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp; <?php echo $branch?></h5><h5>Year&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp; <?php echo $year?></h5>
          <h5>Shared by&nbsp;:&nbsp;&nbsp; <?php echo $user?></h5>
      </div>      
      <div class="post">
        <h4>Comments</h4>
        <?php echo $comment;?><br>
        <div class="comment-box" style="margin-top:20px;width: 100%;">
        <?php if(isset($_SESSION['usr_id'])!="") {?>
        <form method="post">
          <span style = "margin-left:0;margin-right:0;width:100%;" class="input input--jiro">
          <textarea name = "comment" style = "font-size:12px;border:none;" class="input__field input__field--jiro"></textarea>
          <label style = "font-size:12px; padding-bottom:20px;" class="input__label input__label--jiro" for="input-11">
            <span class="input__label-content input__label-content--jiro">Your Comment</span>
          </label>
      </span>
          <br><br><input type = "submit" name = "submit" value = "POST">
          </form>
          <?php } else{?>
        	<form method="post">
            <span style = "margin-left:0;margin-right:0;width:100%;" class="input input--jiro">
          <input name = "name" style = "font-size:12px;border:none;" class="input__field input__field--jiro">
          <label style = "font-size:12px; padding-bottom:20px;" class="input__label input__label--jiro" for="input-11">
            <span class="input__label-content input__label-content--jiro">Name</span>
          </label>
      </span>
            <span style = "margin-left:0;margin-right:0;width:100%;" class="input input--jiro">
          <textarea name = "comment" style = "font-size:12px;border:none;" class="input__field input__field--jiro"></textarea>
          <label style = "font-size:12px; padding-bottom:20px;" class="input__label input__label--jiro" for="input-11">
            <span class="input__label-content input__label-content--jiro">Comment</span>
          </label>
      </span>
          <br><br><input type = "submit" name = "submit1" value = "POST">
          </form>
          <?php }?>
        </div>
    </div>
  </div>
<div class = "side" style = "max-height:800px;overflow:auto;box-shadow: 0 1px 6px rgba(32, 33, 36, 0.28);">
          <h4>Related Stuff</h4>
          <?php echo $side;?>
      	</div>
</section>
    <style>
    @media screen and (max-width: 640px){
      .footer{
        position: relative;
        bottom: 0;
      }
    }
    .reply:hover{
    	cursor: pointer;
    	color:#62a8ea;
    }
    </style>
  </body>
</html>
   <!-- /container -->
    <script src="js/classie.js"></script>
    <script>
      (function() {
        if (!String.prototype.trim) {
          (function() {
            var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
            String.prototype.trim = function() {
              return this.replace(rtrim, "");
            };
          })();
        }
        [].slice.call( document.querySelectorAll( "textarea.input__field" ) ).forEach( function( inputEl ) {
          if( inputEl.value.trim() !== "" ) {
            classie.add( inputEl.parentNode, "input--filled" );
          }
          inputEl.addEventListener( "focus", onInputFocus );
          inputEl.addEventListener( "blur", onInputBlur );
        } );
        [].slice.call( document.querySelectorAll( "input.input__field" ) ).forEach( function( inputEl ) {
          if( inputEl.value.trim() !== "" ) {
            classie.add( inputEl.parentNode, "input--filled" );
          }
          inputEl.addEventListener( "focus", onInputFocus );
          inputEl.addEventListener( "blur", onInputBlur );
        } );
        function onInputFocus( ev ) {
          classie.add( ev.target.parentNode, "input--filled");
        }
        function onInputBlur( ev ) {
          if( ev.target.value.trim() === "" ) {
            classie.remove( ev.target.parentNode, "input--filled" );
          }
        }
      })();
    </script>